eureka:
    instance:
        hostname: localhost
    client:
        fetchRegistry: true
        registerWithEureka: true
        serviceUrl:
            defaultZone: http://localhost:9001/eureka/
    server:
        enableSelfPreservation: 'false  '
server:
    port: 9001
    
spring:
  profiles: default
 