eureka:
    instance:
        hostname: eureka.local
    client:
        fetchRegistry: false
        registerWithEureka: false
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
        enableSelfPreservation: 'false  '
server:
    port: 9001
    
spring:
  profiles: default