server:
    port: 7000
spring:
    datasource:
        password: pwd
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/contrat?serverTimezone=Europe/Paris&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: slo
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
urbanisation-si:
    clairprev:
        limiteNombreContrat: 3


eureka:
    client:
        service-url:
            defaultZone: http://localhost:9001/eureka/

