microservice-produit:
    limiteNombreProduit: 3
spring:
    datasource:
        password: pwd
        url: jdbc:h2:mem:ref_produit_db
        username: slo
    h2:
        console:
            enabled: true
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true

eureka:
    client:
        serviceUrl:
            defaultZone: http://localhost:9001/eureka/