server:
    port: 8000
spring:
    datasource:
        password: pwd
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/previt_db?serverTimezone=Europe/Paris&zeroDateTimeBehavior=CONVERT_TO_NULL
        username: slo
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
urbanisation-si:
    clairprev:
        limiteNombreAssure: 3
        
eureka:
    instance:
      appname: microservice-assure
    client:
        serviceUrl:
            defaultZone: http://localhost:9001/eureka/
        fetchRegistry: true
        registerWithEureka: true



---
spring:
  profiles: microservice-assure01
eureka:
  instance:
    appname: microservice-assure  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka  
server:
  port: 8001   
     
---
spring:
  profiles: microservice-assure02
eureka:
  instance:
    appname: microservice-assure  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka    
server:
  port: 8002
  
---
spring:
  profiles: microservice-assure03
eureka:
  instance:
    appname: microservice-assure  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka    
server:
  port: 8003
  
---
spring:
  profiles: microservice-assure04
eureka:
  instance:
    appname: microservice-assure  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka    
server:
  port: 8004  
  
---
spring:
  profiles: microservice-assure05
eureka:
  instance:
    appname: microservice-assure  # ==> This is a instance of ABC-SERVICE
  client:   
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka    
server:
  port: 8005
